# Generated by Django 5.1.3 on 2025-04-14 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocoltype',
            name='user',
        ),
        migrations.AddField(
            model_name='protocoltype',
            name='laboratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.laboratory'),
            preserve_default=False,
        ),
    ]
