# Generated by Django 5.1.3 on 2025-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_protocoltype_user_protocoltype_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='name',
        ),
        migrations.AddField(
            model_name='protocol',
            name='addition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='addition_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='building_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='building_data_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='humidity_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='humidity_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='producer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='producer_name_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='product_name_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='rd_test_building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='rd_test_building_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='rd_test_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='rd_test_method_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='subcontractor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='subcontractor_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='temperature_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='temperature_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='test_type_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
