# Generated by Django 5.1.3 on 2025-04-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_protocol_user_protocol_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.building'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protocol',
            name='status',
            field=models.IntegerField(choices=[(0, 'SAVED'), (1, 'COMPLETED'), (2, 'REQUEST'), (3, 'REJECTED')]),
        ),
    ]
