# Generated by Django 5.1.3 on 2025-03-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_laboratory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='Machines',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='buildings',
        ),
        migrations.AddField(
            model_name='building',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
