# Generated by Django 5.1.3 on 2025-03-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clients',
            field=models.ManyToManyField(blank=True, to='api.client'),
        ),
    ]
