# Generated by Django 5.1.3 on 2025-04-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_protocol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
