# Generated by Django 5.1.3 on 2025-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_certificate_alter_machines_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.certificate'),
        ),
    ]
