# Generated by Django 5.1.3 on 2025-04-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_machines_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='created_at',
        ),
    ]
