# Generated by Django 5.1.3 on 2025-04-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_machines_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='created_at',
        ),
    ]
