# Generated by Django 5.1.3 on 2025-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_machines_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='certificate_expiry_date',
            field=models.DateField(),
        ),
    ]
