# Generated by Django 5.1.3 on 2025-03-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_building_address_alter_building_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='prefix',
            field=models.CharField(default='SB', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='api.client'),
        ),
    ]
