# Generated by Django 5.1.3 on 2025-04-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_position_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
    ]
