# Generated by Django 5.1.3 on 2025-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_building_prefix_alter_building_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='prefix',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
