# Generated by Django 5.1.3 on 2025-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_position_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='language',
            field=models.CharField(blank=True, default='ru', max_length=2),
        ),
    ]
