# Generated by Django 5.1.3 on 2025-03-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_building_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratory'),
        ),
    ]
