# Generated by Django 5.1.3 on 2025-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_protocol_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
