# Generated by Django 5.1.3 on 2025-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_protocol_building_protocol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='tester',
            field=models.CharField(default='Tester', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='tester_en',
            field=models.CharField(default='Tester', max_length=200),
            preserve_default=False,
        ),
    ]
