# Generated by Django 5.1.3 on 2025-05-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_protocol_tester_protocol_tester_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='tester_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
