# Generated by Django 5.1.3 on 2025-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_protocol_tester_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='building_protocol_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
