# Generated by Django 5.1.3 on 2025-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_protocol_building_protocol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='saved_machines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
