# Generated by Django 5.1.3 on 2025-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_laboratory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
